MYRIAD_TOP = ../../..

.PHONY: all


# As this module must be generated to share MyriadGUI constants:
#
# (see the gui_constants module and the %_generated.beam target in
# GNUmakerules-automatic.inc)
#
EXTRA_BEAM_FILES = gui_generated.beam


include $(MYRIAD_TOP)/GNUmakesettings.inc
